server:
  port: 8088
spring:
  r2dbc:
    username: root
    password: 0601E770939B74CE08D49F08099B2833
    url: r2dbc:mysql://43.138.242.23:3306/webflux_test?character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  data:
    redis:
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
      host: 43.138.242.23
      #Redis服务器连接端口
      port: 6379
      #Redis服务器连接密码（默认为空）
      password: 0601E770939B74CE08D49F08099B2833
      #连接超时时间（毫秒）
      timeout: 30000

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 关闭字符画
  is-print: false
oauth2:
  github:
    # 替换为自己的 Client ID 和 Client Secret
    clientId: 3becadba41cf1a88646e
    clientSecret: 5dc44c3c5b305e34cdc20d8e4033515f4e0b9390
forest:
  log-enabled: false
  connect-timeout: 8000        # 连接超时时间，单位为毫秒
  read-timeout: 8000           # 数据读取超时时间，单位为毫秒
